In [ ]:
# numPY --- it is used in mathamatics
# data structure of numpy is multidimensional array
# [1 , 2 , 3]>>-- one dimenstional array.
# [[1 , 2 , 3 ][ 4 , 5, 6]]>>--- two dimenstinaol array.
# it is only homogeneous not hetrogeneous.
import numpy as np

In [ ]:
 import numpy as np



In [ ]:
# one dimensional
oned_array = np.array([1 , 2 , 3])
print(oned_array)

[1 2 3]


In [ ]:
# two demensional array
two_d_array = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
two_d_array = np.array ([[1 , 2 , 3 , 4] , [4 , 5 , 6 , 7]]) # Corrected the second inner list to have 4 elements
print(two_d_array)   # it is also the column vector

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
print(two_d_array.shape)

(2, 4)


In [ ]:
# row vector
row_vector = np.array([[1 , 2 , 3]])
print(row_vector)

[[1 2 3]]


In [ ]:
print(row_vector.shape)

(1, 3)


In [ ]:
# column vector
column_vector = np.array([[1,2] , [3,4] , [3,5]])
print(column_vector)

[[1 2]
 [3 4]
 [3 5]]


In [ ]:
print(column_vector.shape)

(3, 2)


In [ ]:
row_vector = np.array([[1 , 2 , 3]])
print(row_vector)


[[1 2 3]]


In [ ]:
# to transpose (row to column and column to row)
column_vector = row_vector.transpose()
print(column_vector)

[[1]
 [2]
 [3]]


In [ ]:
First_vector = column_vector.transpose()
print(First_vector)

[[1 3 3]
 [2 4 5]]


In [ ]:
# to find dimension
column_vector.ndim

2

In [ ]:
# for size
column_vector.size

3

In [ ]:
print(column_vector)

[[1]
 [2]
 [3]]


In [ ]:
twod_array = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
print(twod_array)



[[1 2 3]
 [4 5 6]]


In [ ]:
print(twod_array.shape)

(2, 3)


In [ ]:
# defined row
print(twod_array[0])

[1 2 3]


In [ ]:
print(oned_array[1])

2


In [ ]:
print(twod_array[1][2])

6


In [ ]:
print(twod_array[1][1])

5


In [ ]:
print(twod_array[0,2])

3


In [ ]:
# slicing
print(twod_array[0:2 , 0:2])

[[1 2]
 [4 5]]


In [ ]:
# three dimenstional array
threed_array = np.array([[[1 , 2 , 3] , [4 , 5 , 6]] , [[7 , 8 , 9] , [10 , 11 , 12]]])
print(threed_array)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
threed_array = np.random.randint(1 , 10 , size=(3 , 3)) # 1,10 = To defined the random values in between 1 to 10|3,3 = to
# defined the type of matrix.
print(threed_array)

[[3 2 9]
 [9 1 6]
 [3 1 9]]


In [ ]:
import numpy as np
mat3 = np.random.randint(1 , 20 ,(3 , 3))
print(mat3)

[[ 7  9  5]
 [17  1 12]
 [18  6 15]]


In [ ]:
zeos_array = np.zeros((3 , 3) , dtype=int) # by-deafault it gives in the form of float value
print(zeos_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_array = np.ones((3 , 3), dtype = float)
print(ones_array)
print(ones_array*30)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]


In [ ]:
print(ones_array*90)

[[90 90 90]
 [90 90 90]
 [90 90 90]]


In [ ]:
my_array = np.full((3 , 3), 10) # in question ask make a matrix that all have same no.
print(my_array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
my_array = np.array([1 , 2, 3 , 4])
print(my_array)

[1 2 3 4]


In [ ]:
power_array = np.power(my_array , 2) # to power the array
print(power_array)

[ 1  4  9 16]


In [ ]:
print(my_array)

[1 2 3 4]


In [ ]:
exp_array = np.exp(threed_array) # to find the exponition of the ARRAY
print(exp_array)

[[2.00855369e+01 7.38905610e+00 8.10308393e+03]
 [8.10308393e+03 2.71828183e+00 4.03428793e+02]
 [2.00855369e+01 2.71828183e+00 8.10308393e+03]]


In [ ]:
log_array = np.log(my_array)
print(log_array)

[0.         0.69314718 1.09861229 1.38629436]


In [ ]:
log2_array = np.log2(my_array)
print(log2_array)


[0.        1.        1.5849625 2.       ]


In [ ]:
log10_array = np.log10(my_array)
print(log10_array)

[0.         0.30103    0.47712125 0.60205999]


In [ ]:
ar1 = np.array([1,2,3])
print(ar1)

[1 2 3]


In [ ]:
print(ar1[2])

3


In [ ]:
ar2 = np.array([[2,3,4,5,6],[3,1,6,4,7],[2,4,1,5,6]])
print(ar2)

[[2 3 4 5 6]
 [3 1 6 4 7]
 [2 4 1 5 6]]


In [ ]:
print(ar2.shape)

(3, 5)


In [ ]:
print(ar2[1][1])

1


In [ ]:
print(ar1[1:3])

[2 3]


In [ ]:
print(ar1[2])

3


In [ ]:
ar2 = np.array([[2,3,4,5,6],[3,1,6,4,7],[2,4,1,5,6]])
print(ar2)

[[2 3 4 5 6]
 [3 1 6 4 7]
 [2 4 1 5 6]]


In [ ]:
print(ar2[0:3:1 , 1:5])

NameError: name 'ar2' is not defined

In [ ]:
row_vector = np.arange(1, 6).reshape(1, 5) # if
print(row_vector)
print("Shape" , row_vector.shape)


[[1 2 3 4 5]]
Shape (1, 5)


In [ ]:
to_d_array = np.array([[1,2,4] , [2,4,2] , [2,4,6]])
print(to_d_array)

[[1 2 4]
 [2 4 2]
 [2 4 6]]


In [ ]:
print(to_d_array[0:3,1:3])

[[2 4]
 [4 2]
 [4 6]]
